apiVersion : apps/v1
kind: Deployment
metadata:
  name: examdevopscontainerregistry 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examdevopscontainerregistry
  template:
    metadata:
      labels:
        app: examdevopscontainerregistry 
    spec:
      containers:
        - name: examdevopscontainerregistry 
          image: examdevopscontainerregistry.azurecr.io/pipelineazuredeploy
          ports:
          - containerPort: 8080
